version: '2.1'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lunatech_imdb
    ports:
      - "5430:5432"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: none
    shm_size: 1g

  postgres-init:
    image: ghcr.io/lunatech-labs/lunatech-imdb-assessment-db-loader:1.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=lunatech_imdb
      - MINIMAL_DATASET=true
      - FORCE_IMPORT=false
